import { IContact } from "../interfaces";

export const contactList: IContact[] = [
  {
    name: "Alberto",
    lastName: "Almeida",
    surname: "Beto",
    telephone: ["(95) 99171-8840"],
    email: "albertoalmeida@gmail.com",
    address: {
      cep: "69.314-338",
      street: "Raimundo de Castro",
      number: "676",
      neighborhood: "Dr. Sílvio Leite",
      complement: "CASA",
      city: "Boa Vista",
      state: "RR",
    },
    tag: "Trabalho",
  },
  {
    name: "Bianca",
    lastName: "Coreia",
    surname: "",
    telephone: ["(98) 99451-6850"],
    email: "bianca@gmail.com",
    address: {
      cep: "69.314-338",
      street: "Raimundo de Castro",
      number: "676",
      neighborhood: "Dr. Sílvio Leite",
      complement: "CASA",
      city: "Boa Vista",
      state: "RR",
    },
    tag: "Família",
  },
  {
    name: "Ciclano",
    lastName: "Almeida",
    surname: "Ciclaninho",
    telephone: ["(95) 99171-8840"],
    email: "cilclano@gmail.com",
    address: {
      cep: "69.314-338",
      street: "Raimundo de Castro",
      number: "676",
      neighborhood: "Dr. Sílvio Leite",
      complement: "CASA",
      city: "Boa Vista",
      state: "RR",
    },
    tag: "Trabalho",
  },
  {
    name: "Fulano",
    lastName: "de Tal",
    surname: "Fulaninho",
    telephone: ["(95) 99165-8240"],
    email: "fulano@gmail.com",
    address: {
      cep: "69.038-380",
      street: "Raimundo de Castro",
      number: "676",
      neighborhood: "Dr. Sílvio Leite",
      complement: "CASA",
      city: "Boa Vista",
      state: "RR",
    },
    tag: "Amigos",
  },
  {
    name: "Joana",
    lastName: "Cavalcante",
    surname: "",
    telephone: ["(92) 8117-6319"],
    email: "joanacavalcante@gmail.com",
    address: {
      cep: "01001-000",
      street: "Rua dos Bobos",
      number: "0",
      neighborhood: "Bairro dos Bobos",
      complement: "",
      city: "São Paulo",
      state: "SP",
    },
    tag: "Família",
  },
  {
    name: "João",
    lastName: "Silva",
    surname: "Joãozinho",
    telephone: ["(92) 8117-6319"],
    email: "joaosilva@gmail.com",
    address: {
      cep: "01001-000",
      street: "Rua dos Bobos",
      number: "0",
      neighborhood: "Bairro dos Bobos",
      complement: "",
      city: "São Paulo",
      state: "SP",
    },
    tag: "Família",
  },
  {
    name: "Leandro",
    lastName: "Carvalho",
    surname: "Leo",
    telephone: ["(95) 99171-8840"],
    email: "leandrofelipe@gmail.com",
    address: {
      cep: "69.314-338",
      street: "Raimundo de Castro Barros",
      number: "0",
      neighborhood: "Dr. Sílvio Leite",
      complement: "",
      city: "Boa Vista",
      state: "RR",
    },
    tag: "Faculdade",
  },
  {
    name: "Leonardo",
    lastName: "Felipe",
    surname: "Leo",
    telephone: ["(95) 99171-8840"],
    email: "leonardofelipe931@gmail.com",
    address: {
      cep: "69.314-338",
      street: "Raimundo de Castro Barros",
      number: "0",
      neighborhood: "Dr. Sílvio Leite",
      complement: "",
      city: "Boa Vista",
      state: "RR",
    },
    tag: "Faculdade",
  },
];
