import { IContact } from "../interfaces";

export const contactList: IContact[] = [
  {
    name: "João",
    lastName: "Silva",
    surname: "Santos",
    telephone: ["(92) 8117-6319"],
    email: "leonardofelipe931@gmal.com",
    address: {
      cep: "01001-000",
      street: "Rua dos Bobos",
      number: "0",
      neighborhood: "Bairro dos Bobos",
      complement: "",
      city: "São Paulo",
      state: "SP",
    },
    tag: "Família",
  },
  {
    name: "Leonardo",
    lastName: "Felipe",
    surname: "Leo",
    telephone: ["(95) 99171-8840"],
    email: "leonardofelipe931@gmal.com",
    address: {
      cep: "69.314-338",
      street: "Rua dos Bobos",
      number: "0",
      neighborhood: "Bairro dos Bobos",
      complement: "",
      city: "Boa Vista",
      state: "RR",
    },
    tag: "Faculdade",
  },
  {
    name: "Fulano de Tal",
    lastName: "",
    surname: "Leo",
    telephone: ["(95) 99171-8840"],
    email: "leonardofelipe931@gmal.com",
    address: {
      cep: "69.314-338",
      street: "Raimundo de Castro",
      number: "676",
      neighborhood: "Dr. Sílvio Leite",
      complement: "CASA",
      city: "Boa Vista",
      state: "RR",
    },
    tag: "Amigos",
  },
  {
    name: "Ciclano",
    lastName: "Almeida",
    surname: "Leo",
    telephone: ["(95) 99171-8840"],
    email: "leonardofelipe931@gmal.com",
    address: {
      cep: "69.314-338",
      street: "Raimundo de Castro",
      number: "676",
      neighborhood: "Dr. Sílvio Leite",
      complement: "CASA",
      city: "Boa Vista",
      state: "RR",
    },
    tag: "Trabalho",
  },
  {
    name: "Alberto",
    lastName: "Almeida",
    surname: "Leo",
    telephone: ["(95) 99171-8840"],
    email: "leonardofelipe931@gmal.com",
    address: {
      cep: "69.314-338",
      street: "Raimundo de Castro",
      number: "676",
      neighborhood: "Dr. Sílvio Leite",
      complement: "CASA",
      city: "Boa Vista",
      state: "RR",
    },
    tag: "Trabalho",
  },
];
